Tracker:AddItems("items/__options.json")

Tracker:AddItems("items/abilities.json")
Tracker:AddItems("items/bosses.json")
Tracker:AddItems("items/characters.json")
Tracker:AddItems("items/collectibles.json")
Tracker:AddItems("items/dungeon_key_items.json")
Tracker:AddItems("items/fish.json")
Tracker:AddItems("items/golems.json")
Tracker:AddItems("items/key_items.json")
Tracker:AddItems("items/recipes.json")
Tracker:AddItems("items/wheels.json")

Tracker:AddItems("items/dlc_abilities.json")
Tracker:AddItems("items/dlc_bosses.json")
Tracker:AddItems("items/dlc_characters.json")
Tracker:AddItems("items/dlc_collectibles.json")
Tracker:AddItems("items/dlc_goodie_bags.json")
Tracker:AddItems("items/dlc_key_items.json")
Tracker:AddItems("items/dlc_recipes.json")
Tracker:AddItems("items/dlc_skills.json")