Tracker:AddItems("items/__options.json")

Tracker:AddItems("items/bosses.json")
Tracker:AddItems("items/characters.json")
Tracker:AddItems("items/dungeon_keys.json")
Tracker:AddItems("items/fish.json")
Tracker:AddItems("items/golems.json")
Tracker:AddItems("items/key_items.json")
Tracker:AddItems("items/mirth_builder.json")
Tracker:AddItems("items/question_packs.json")
Tracker:AddItems("items/recipes.json")
Tracker:AddItems("items/wheels.json")
