Tracker:AddItems("items/__options.json")

Tracker:AddItems("items/bosses.json")
Tracker:AddItems("items/characters.json")
Tracker:AddItems("items/collectibles.json")
Tracker:AddItems("items/dungeon_key_items.json")
Tracker:AddItems("items/fish.json")
Tracker:AddItems("items/golems.json")
Tracker:AddItems("items/key_items.json")
Tracker:AddItems("items/recipes.json")
Tracker:AddItems("items/wheels.json")
